### ISSUE TITLE
Data binding on change causes multiple markers

### ISSUE THREAD

**Issue by tareqimbasher** [Vheissu/aurelia-google-maps#21]
When we are binding an object's property to the address property like this:

`<google-map address.two-way="project.Address.fullAddress"
                                            zoom="15"></google-map>`

and when the `fullAddress` property changes the marker on the map changes to the new address, however the old address marker persists. This is especially intrusive when the address changes to another address close by, the two markers are close and obvious, causing confusion.

Is this something I am doing? Or is it not meant to be used with data binding?

Thank you for your awesome plugin!

**Comment by tomtomau** [comment]
Hmm, it's not supposed to have any two-way data binding yet, however it should definitely update to the new marker and remove the old one. The current expected behaviour is to clear all the markers and redraw them all when the array of markers changes. I'm not sure if the two-way data binding is changing anything but I can't imagine so. I'll hopefully try to put a failing plunkr together soon and report back here.

**Comment by tomtomau** [comment]
Sorry for the delay @tareqimbasher - I've fixed this pending review :)

**Comment by Vheissu** [comment]
@tareqimbasher I have added in @tomtomau changes, let me know if this resolves the issue for you.

**Comment by tareqimbasher** [comment]
@tomtomau @Vheissu Thank you both very much. I will definitely give this a try and let you know soon. :+1:
